api = "0.7"

[buildpack]
  description = "A buildpack for starting a passenger server for a Ruby app"
  homepage = "https://github.com/paketo-buildpacks/passenger"
  id = "paketo-buildpacks/passenger"
  keywords = ["ruby", "passenger"]
  name = "Paketo Buildpack for Passenger"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/passenger/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependency-constraints]]
    constraint = "7.*"
    id = "curl"
    patches = 1

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"
